flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')
    teaser_title = StringField('Teaser Title', validators=[DataRequired()])
    teaser_details = StringField('Teaser Details', validators=[DataRequired()])
    teaser_caption = TextAreaField('Teaser Caption', validators=[DataRequired()] )
    teaser_img = StringField('Teaser Image', validators=[DataRequired()] )
    teaser_content = TextAreaField('Teaser Content', validators=[DataRequired()] )
    teaser_wkid = StringField('Teaser Weekly Id', validators=[DataRequired()])

flaskblog/main/routes.py
from flask import render_template, request, Blueprint, url_for, redirect, current_app
from flask_login import current_user
from flaskblog.models import Post

main = Blueprint('main', __name__)



#@main.route("/home")
#def home():
#    page = request.args.get('page', 1, type=int)
#    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
#    return render_template('post.html', posts=posts)

@main.route("/intro")
def intro():
    if current_user.is_authenticated:
        return render_template('intro.html')
    else:
        return redirect(url_for('users.index'))

@main.route("/methods")
def methods():
    if current_user.is_authenticated:
        return render_template('methods.html')
    else:
        return redirect(url_for('users.index'))

@main.route("/trades")
def trades():
    if current_user.is_authenticated:
        page = request.args.get('page', 1, type=int)
        posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
        return render_template( 'trades.html', posts=posts)
    else:
        return redirect(url_for('users.index'))

@main.route("/pnl")
def pnl():    
    if current_user.is_authenticated:
        return render_template('pnl.html')
    else:
        return redirect(url_for('users.index'))

@main.route("/about")
def about():
    if current_user.is_authenticated:        
        return render_template('about.html', rp=current_app.root_path, ip=current_app.instance_path, title='About')
    else:
        return redirect(url_for('users.index'))

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user, teaser_title=form.teaser_title.data, teaser_details=form.teaser_details.data,teaser_caption=form.teaser_caption.data, teaser_img=form.teaser_img.data, teaser_content=form.teaser_content.data, teaser_wkid=form.teaser_wkid.data)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.intro'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    if len(post.teaser_wkid) != 0:
        weekly = post.teaser_wkid
    else:
        weekly = ""        
    return render_template('post.html', weekly=weekly, title=post.title, post=post)

@posts.route("/embed_viewer/<weekly_id>")
def embed_viewer(weekly_id):
    return render_template('embed_viewer.html', weekly=weekly_id, title="embed viewer")

@posts.route("/detach_viewer/<weekly_id>")
def detach_viewer(weekly_id):
    return render_template('detach_viewer.html', weekly=weekly_id, title="detach viewer")

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.teaser_title = form.teaser_title.data
        post.teaser_details = form.teaser_details.data
        post.teaser_caption = form.teaser_caption.data
        post.teaser_img = form.teaser_img.data
        post.teaser_content = form.teaser_content.data
        post.teaser_wkid = form.teaser_wkid.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title        
        form.content.data = post.content
        form.teaser_title.data = post.teaser_title
        form.teaser_details.data = post.teaser_details
        form.teaser_caption.data = post.teaser_caption
        form.teaser_img.data = post.teaser_img
        form.teaser_content.data = post.teaser_content
        form.teaser_wkid.data = post.teaser_wkid
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.intro'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/", methods=['GET', 'POST'])
def index():
    if current_user.is_authenticated:
        return redirect(url_for('main.intro'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            if user.username == "GuestUser":
                login_user(user, remember=form.remember.data)
                return redirect(url_for('main.intro'))
            else:
                flash('Incorrect Guest Id. Please check email', 'danger')
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('frontend.html', title='Login', form=form)




@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.intro'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated and current_user.username != "GuestUser":
        return redirect(url_for('main.intro'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.intro'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    #return redirect(url_for('main.intro'))
    return redirect(url_for('users.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=4)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.intro'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.intro'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}


<style>
#myVideo {
  position: fixed;
  right: 0;
  bottom: 0;
  min-width: 100%; 
  min-height: 100%;
}

.
</style>
<body>

<video autoplay muted loop id="myVideo">
  <source src="/static/videoplayback2.mp4" type="video/mp4">
  Your browser does not support HTML5 video.
</video>

<div class="intro-page" style="max-height: 77vh;overflow:auto;font-size:14px;line-height:21px;"> 
  <div class="intro-inner-div" style="color:white;">
  	<div class="container-fluid col-md-10">
  		<h1>Disclosure</h1>
  		<p>
  			Trading security futures involves the risk of loss, including the possibility of loss greater than your initial investment. Prior to buying or selling a security future, a person must receive a copy of the Risk Disclosure Statement for Security Futures Contracts.
				<br>
				<br>WebSite Disclaimer: Use at your own risk. While we endeavour to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, services related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk. In no event will we be liable for any loss or damage, including, without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arising out of, or in connection with, the use of this website. This presentation is for educational purposes only. Opinions or points of view expressed in this presentation represent the view of the presenter only. Nothing in this presentation constitutes legal, technical, financial advice. The individuals appearing in this presentation, if any, are depicted for illustrative purpose only.
				<br>
				<br>Copyright Disclaimer: Under section 107 of the Copyright Act of 1976, allowance is made for “fair use” for purposes such as criticism, comment, news reporting, teaching, scholarship, education and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Educational or personal use tips the balance in favor of fair use.
				<br>
        <br>
			</p>
		</div>
	</div>
</div>
</body>


{% endblock content %}  

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.teaser_title.label(class="form-control-label") }}
                {% if form.teaser_title.errors %}
                    {{ form.teaser_title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.teaser_title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.teaser_details.label(class="form-control-label") }}
                {% if form.teaser_details.errors %}
                    {{ form.teaser_details(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_details.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.teaser_details(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.teaser_caption.label(class="form-control-label") }}
                {% if form.teaser_caption.errors %}
                    {{ form.teaser_caption(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_caption.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.teaser_caption(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.teaser_img.label(class="form-control-label") }}
                {% if form.teaser_img.errors %}
                    {{ form.teaser_img(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_img.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.teaser_img(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div  class="form-group">
                {{ form.teaser_content.label(class="form-control-label") }}
                {% if form.teaser_content.errors %}
                    {{ form.teaser_content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                     {{ form.teaser_content(class="form-control form-control-lg") }} 
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.teaser_wkid.label(class="form-control-label") }}
                {% if form.teaser_wkid.errors %}
                    {{ form.teaser_wkid(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.teaser_wkid.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.teaser_wkid(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info" ) }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}

flaskblog/templates/detach_viewer.html
<!DOCTYPE html>
<html>
<style>
	.center{
	width:100%;
	height:51vw;
	margin: 0;
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%)
	}

  
  .blink {
    animation: blinker 12.0s ease-out infinite;
    color: white;
    font-size: 14px;
    background-color:#000000;
  }
  @keyframes blinker {  
    100% { opacity: 0; }
  }


</style>
  <div class="grid"> 
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

      <!-- site font -->
      <link href='http://fonts.googleapis.com/css?family=Lobster+Two' rel='stylesheet' type='text/css'>

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

      <!-- local CSS-->
      
      <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}"> -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='study.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='modal.css') }}">
    </head>
    <body>
    <backdrop>
			<center>
    			<p class="blink" ><br>--->allow a moment for data to load, maximize window, click center of screen to set focus, pgdwn for data<---<br><br></p>
			</center>
			<embed class="center" src="/static/pdf/weekly{{ weekly }}.pdf#view=Fit&toolbar=0&navpanes=0&scrollbar=0">
		</backdrop>
		</body>
	</div>
</html>
	

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div style="height:auto;background-color:transparent;border:none;">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
            </small>
        </div>
    </div>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section" style="border:none;">
    <img class="article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <center><br><h3 class="hero-header">{{ post.title }}</h3><hr><br></center>
      {% if weekly |length %}
      <center><button onclick="myDetach()">View Trades</button></center>
      <!--<center><sub><b>(click view trades->maximize window->pause to load->set focus by clicking center of screen->page down)</b></sub></center>-->
      <br>
      <br>
      <script>
        function myDetach() {
        var myWin = window.open( '/detach_viewer/{{weekly}}', 'myWindow', 'width=990,height=680');
        myWin.moveTo(600, 300);
        //maximize window
        //myWin.resizeTo(window.screen.availWidth, window.screen.availHeight);
        myWin.focus();
      }
      </script>
      {% endif %}
      <!--<div class="adjust-doc-border-intro doc-clear" style="overflow:auto;flex:auto;"> -->
      <br><H6>TRADES TABULATED</H6><br>
      {{ post.content|safe }}
      <!--</div>-->
    <div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/trades.html
{% extends "layout.html" %}
{% block content %}
<div class="intro-page" style="height:82vh;">
  <br><h1 class="hero-header adjust-doc-boarder", style="text-align: center;">trades executed daily</h1><hr><br>
  <div class="intro-inner-div" style="height:60vh;">
    {% for post in posts.items %}
      <div class="adjust-doc-border" style="border:1px solid black;background-image: linear-gradient(-45deg, #9ba6b1, white);">
        <a style="color:black" href="{{ url_for('posts.post', post_id=post.id) }}"><h3 class="teaser-title" style="background-color:transparent"> {{ post.teaser_title }}</a><span class="teaser-details">{{ post.teaser_details }}</span></h3>
        <img class= "teaser-pic doc-float-l" src="{{ post.teaser_img }}">
        <p class="teaser-content" style="font-size: 16px;"><br>{{ post.teaser_caption }}</p>
        <div class="doc-clear"></div>
      </div>
      <br>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-primary btn-lg mb-8" href="{{ url_for('main.trades', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-primary btn-lg mb-8" href="{{ url_for('main.trades', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<div class="intro-page" style="height: 77vh;overflow: auto;"> 
  <div class="intro-inner-div" style="height:auto;background-color:white;border-radius:5px;">
    <center><br><h1 class="hero-header">Posts by {{ user.username }} ({{ posts.total }})</h1><hr></center>
    {% for post in posts.items %}
        <article class="media content-section" style="max-height:280px;">
          <img class="article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <center><a href="{{ url_for('posts.post', post_id=post.id) }}"><h3 class="hero-header"><b>{{ post.title }}</b></h3></a>
            <p class="teaser-content" >(click title to read more)............</p></center>
            <p class="teaser-content" ><div style="overflow:hidden;max-height:120px;">
              {{ post.content|safe }}
            </p>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-primary btn-lg mb-8" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-primary-info btn-lg mb-8" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock content %}